const $=id=>document.getElementById(id);
const names={WATER:'Tôi muốn uống nước.',FOOD:'Tôi muốn ăn.',NO:'Không.'};
const tabs=['overview','firmware','analysis','demo','experiment'];
function route(){const key=location.hash.slice(1);const tab=tabs.includes(key)?key:'overview';for(const id of tabs)$(id).hidden=id!==tab;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.tab===tab)));if(tab==='analysis')draw();if(tab!=='demo')window.speechSynthesis?.cancel();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.tab;});window.addEventListener('hashchange',route);
$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('notice').textContent='Đã sao chép link màn hình này.';}catch{$('notice').textContent='Sao chép địa chỉ trên thanh trình duyệt để chia sẻ.';}};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('notice').textContent='Dùng chế độ toàn màn hình của trình duyệt.';}};
fetch('GestureDetector.h').then(r=>{if(!r.ok)throw Error();return r.text();}).then(t=>$('source').textContent=t).catch(()=>$('source').textContent='Không tải được mã nguồn. Hãy tải lại trang.');
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
let points=[];
function generate(){const gesture=$('gesture').value;points=Array.from({length:201},(_,i)=>{const t=i/50;const envelope=Math.max(0,Math.min(1,(t-.5)*3,(3.5-t)*3));const angle=gesture==='NO'?30*Math.sin(2*Math.PI*2*t)*envelope:(gesture==='WATER'?-30:30)*envelope;return [t,angle+(Math.random()-.5)*1.5];});draw();}
function draw(){const c=$('chart');if($('analysis').hidden)return;const w=c.clientWidth,h=320,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const x=t=>48+t/4*(w-68),y=v=>h/2-v/45*(h/2-25);ctx.font='12px system-ui';ctx.lineWidth=1;for(const v of [-40,-22,0,22,40]){ctx.strokeStyle=Math.abs(v)===22?'#b88c38':'#e0e7dc';ctx.setLineDash(Math.abs(v)===22?[5,5]:[]);ctx.beginPath();ctx.moveTo(45,y(v));ctx.lineTo(w-15,y(v));ctx.stroke();ctx.fillStyle='#67796d';ctx.fillText(v+'°',4,y(v)+4);}ctx.setLineDash([]);for(let t=0;t<=4;t++)ctx.fillText(t+'s',x(t)-6,h-4);ctx.beginPath();ctx.strokeStyle='#2d7256';ctx.lineWidth=2.5;points.forEach(([t,v],i)=>i?ctx.lineTo(x(t),y(v)):ctx.moveTo(x(t),y(v)));ctx.stroke();}
$('generate').onclick=generate;$('gesture').onchange=generate;window.addEventListener('resize',draw);
$('csv').onclick=()=>download('bandw-simulated-'+$('gesture').value+'.csv','time_s,angle_deg,source\n'+points.map(([t,v])=>`${t.toFixed(2)},${v.toFixed(3)},SIMULATED`).join('\n'));
const python=`# Dữ liệu mô phỏng BandW — không phải kết quả đo thực\n# Cài: python -m pip install matplotlib\n# Chạy: python plot_bandw.py bandw-simulated-WATER.csv\nimport csv\nimport sys\nimport matplotlib.pyplot as plt\n\nwith open(sys.argv[1], encoding="utf-8-sig") as f:\n    rows = list(csv.DictReader(f))\ntime = [float(row["time_s"]) for row in rows]\nangle = [float(row["angle_deg"]) for row in rows]\nplt.plot(time, angle, color="#2d7256")\nfor threshold in (-22, 22):\n    plt.axhline(threshold, linestyle="--", color="#b88c38")\nplt.title("BandW - SIMULATED DATA")\nplt.xlabel("Time (s)")\nplt.ylabel("Tilt angle (degrees)")\nplt.grid(alpha=0.2)\nplt.tight_layout()\nplt.show()\n`;
$('python-code').textContent=python;$('python').onclick=()=>download('plot_bandw.py',python);
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{const cmd=b.dataset.command;$('phrase').textContent=names[cmd];$('command').textContent=cmd+' · Mô phỏng';if(!('speechSynthesis'in window)){$('voice').textContent='Trình duyệt không hỗ trợ đọc. Bạn vẫn xem được câu nói.';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(names[cmd]);u.lang='vi-VN';const vi=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('vi'));if(vi)u.voice=vi;u.rate=.9;u.onend=()=>$('voice').textContent='Đã đọc xong.';u.onerror=e=>{if(e.error!=='canceled'&&e.error!=='interrupted')$('voice').textContent='Không phát được âm thanh. Kiểm tra giọng tiếng Việt trên thiết bị.';};$('voice').textContent='Đang đọc câu mô phỏng…';speechSynthesis.speak(u);});$('stop').onclick=()=>{window.speechSynthesis?.cancel();$('voice').textContent='Đã dừng đọc.';};
let trials=[];try{const saved=JSON.parse(localStorage.getItem('bandw-research-trials')||'[]');if(Array.isArray(saved))trials=saved.filter(r=>r&&names[r.expected]&&(names[r.actual]||r.actual==='NONE')&&typeof r.notes==='string');}catch{}
function save(){try{localStorage.setItem('bandw-research-trials',JSON.stringify(trials));}catch{$('notice').textContent='Không lưu được trên máy. Hãy xuất CSV để giữ kết quả.';}}
function render(){const correct=trials.filter(r=>r.expected===r.actual).length;$('stats').textContent=trials.length?`${trials.length} lần thử · ${correct} đúng · ${(correct/trials.length*100).toFixed(1)}% (tự nhập)`:'Chưa có kết quả. Thử vòng tay rồi ghi quan sát của bạn.';$('rows').replaceChildren();trials.forEach((r,i)=>{const row=document.createElement('tr');for(const value of [i+1,r.expected,r.actual,r.notes]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}const cell=document.createElement('td'),remove=document.createElement('button');remove.textContent='Xóa';remove.setAttribute('aria-label',`Xóa lần thử ${i+1}`);remove.onclick=()=>{trials.splice(i,1);save();render();};cell.append(remove);row.append(cell);$('rows').append(row);});}
$('trial').onsubmit=e=>{e.preventDefault();trials.push({expected:$('expected').value,actual:$('actual').value,notes:$('notes').value.trim()});save();render();$('notes').value='';};
const csvCell=v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
$('export').onclick=()=>download('bandw-observations.csv','\ufefftrial,expected,actual,notes,source\n'+trials.map((r,i)=>[i+1,r.expected,r.actual,r.notes,'USER_ENTERED'].map(csvCell).join(',')).join('\n'));
generate();render();route();
